### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Kafkamorph** [weex/Live-bitcoin-transactions#3]
Very lean and effective.

However:

_1KdhdQgZJ1EoFPUJYQWyqZokoaPsoNkE7Z got 0.00000546
Traceback (most recent call last):
  File "ws1.py", line 25, in <module>
    print out['addr'] + ' got ' + str( Decimal( out['value'] ) / Decimal(100000000.0)) +marker
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'_

**Comment by weex** [comment]
I'm just skipping those outputs with no 'addr' for now. Next step if you're interested would be to see if some other field would be better to print when 'addr' is None.
